language: ruby
rvm:
  - 1.9.3
  - 2.1
  - 2.2
  - jruby-1.7.18
script: "cp spec/rabbitmq.yml.example spec/rabbitmq.yml && bundle exec rake coverage"
services:
  - rabbitmq
notifications:
  email:
    - support@travellink.com.au
  flowdock: e69dcafad1fea15c6b8c76e9ced965af
